apiVersion: apps/v1
kind: Deployment
metadata:
    name: ect-deployment
    namespace: ect
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: ect-container
                  image: ect:latest
                  imagePullPolicy: Never
                  envFrom:
                      - configMapRef:
                            name: backend-config
                  ports:
                      - containerPort: 3000
