apiVersion: apps/v1
kind: Deployment
metadata:
    name: sunshine-daisy-bank-deployment
    namespace: sunshine-daisy-bank
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: sunshine-daisy-bank-container
                  image: sunshine-daisy-bank:latest
                  ports:
                      - containerPort: 3000
