apiVersion: v1
kind: Service
metadata:
    name: ect-service
    namespace: ect
spec:
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: LoadBalancer
