apiVersion: v1
kind: Service
metadata:
    name: sunshine-daisy-bank-service
    namespace: sunshine-daisy-bank
spec:
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: ClusterIP
