apiVersion: apps/v1
kind: Deployment
metadata:
    name: pg-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:latest
                  envFrom:
                      - configMapRef:
                            name: pg-config
                  ports:
                      - containerPort: 5432
                  volumeMounts:
                      - name: postgres-persistent-storage
                        mountPath: /var/lib/postgresql/data
            volumes:
                - name: postgres-persistent-storage
                  persistentVolumeClaim:
                      claimName: pg-pvc
